---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
#install.packages("broom")
library(broom)
```

Histogram, wykres pudełkowy -- dla zmiennych ciągłych
Wykres słupkowy (barplot) -- dla zmiennych dyskretnych, porządkowych lub nominalnych

```{r}
head(diamonds)
```

```{r}
summary(diamonds$price)
```
```{r}
hist(diamonds$price)
hist(diamonds$price, breaks = "fd")
```

```{r}
hist(diamonds$table)
barplot(table(diamonds$table))
```

```{r}
tidy( summary(diamonds$price) )
```

Wykres pudełkowy 

Q3 + 1.5R = Q3 + 1.5 (Q3-Q1) -- wartości odstające z prawej cześci rozkładu
Q1 - 1.5R = Q1 - 1.5 (Q3-Q1) -- wartości odstające z lewej części rozkładu

```{r}
boxplot(price ~ color, data = diamonds)
boxplot(log(price) ~ color, data = diamonds)
```

Wykres rozrzutu (scatter plot)

```{r}
plot(x = diamonds$carat, y = diamonds$price, 
     main = "Zależność między liczbą karatów, a ceną",
     xlab = "Liczba karatów", ylab = "Cena")

plot(x = log(diamonds$carat), y = log(diamonds$price), 
     main = "Zależność między liczbą karatów, a ceną",
     xlab = "Liczba karatów", ylab = "Cena")
```

```{r}
pairs(diamonds[,c("carat", "depth", "price")])
```


