---
title: "R Notebook"
output:
  word_document: default
  html_notebook: default
  html_document:
    df_print: paged
---

```{r}
#install.packages(c("sjPlot", "stargazer", "texreg", "jtools", "huxtable"))
library(sjPlot)
library(jtools)
library(texreg)
library(stargazer)
library(huxtable)
```

Zacznijmy od zbudowania trzech modeli

```{r}
## etykieta dla zmiennej
attr(mtcars$wt, "label") <- "waga"

## typ factor (zmienna jakościowa)
mtcars$cyl <- factor(mtcars$cyl, 
                     levels = c(4, 6, 8),
                     label = c("4ry", "6ść", "8siem"))

model1 <- lm(formula = mpg ~ wt, data = mtcars)
model2 <- lm(formula = mpg ~ am + wt + cyl, data = mtcars)
model3 <- lm(formula = mpg ~ wt + am + cyl + hp, data = mtcars)
```

Zaczniemy od pakiety sjPlot

```{r}
tab_model(
  model1, 
  model2,
  dv.labels = c("Model 1", "Model 2"), ## etykiety dla modeli
  string.pred = "Zmienne", ## etykieta dla zmiennych
  string.est = "Parametr", ## etykieta dla parametrów
  string.se =  "Błąd std.", ## etykieta dla błędu std.
  string.p = "P-value", ## etykieta dla p-value
  show.stat = TRUE, ## pokazanie statystyki t / z / Walda
  show.reflvl = TRUE, ## pokazanie poziomu referncyjnego dla zmiennych jak.
  prefix.labels = "varname", ## pokazanie nazwy zmiennej jak.
  collapse.se = TRUE, ## błędy standardowe poniżej
  digits = 4,  ## 4 miejsca po przecinku
  show.ci = FALSE,  ## brak przedziału ufności
  show.se = TRUE,  ## pokazanie błędów standardowych
  show.aic = TRUE, ## pokazanie statystyki AIC
  emph.p = FALSE,
  CSS = css_theme("cells"),
  file = "../reports/sjplot-modele.html" ## zapis wyniów do pliku HTML
  )
```


Przejdziemy do pakietu `jtools` -- pakiet umożliwia raportowanie wyników regresji do języka markdown, html oraz latex

Centrowanie zmiennych:

$$
z_i = x_i - \bar{x}
$$

```{r}
summ(model = model3,
     vifs = TRUE, 
     center = TRUE, 
     confint = TRUE, 
     pvals = FALSE)
```

Można określić globalne opcje

```{r}
set_summ_defaults(digits = 4, vifs = FALSE)
```

```{r}
export_summs(model1,model2, model3, 
             model.names = c("M1", "M2", "M3") 
             #coefs = c("Waga" = "wt")
             )
```

Przejdzmy teraz do pakietu texreg

screenreg -- języka markdown
texreg -- do LaTeXa
htmlreg -- do pliku html


```{r}
screenreg(l = list(M1 = model1, M2 = model2), 
          single.row = TRUE, 
          stars = 0.001,
          digits = 4,
          star.symbol = "!",
          custom.note = "Uwaga: p < 0.001, należy jednak uważać.",
          caption = "Porównanie wyników",
          bold = 0.05,
          custom.coef.names = c(
            "Wyraz wolny",
            "waga",
            "automat",
            "cyl: 6",
            "cyl: 8"
          ))

```

